import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { providerMark } from "@hraness/design-kit/provider-marks";

const repository = resolve(new URL("..", import.meta.url).pathname);
const outputPath = resolve(repository, "src/ask-ai-marks.generated.ts");

const askAiMarkIdentities = [
  ["chatgpt", "openai"],
  ["claude", "claude"],
  ["perplexity", "perplexity"],
  ["grok", "xai"],
] as const;

async function render(): Promise<string> {
  const uiManifest = JSON.parse(
    await readFile(resolve(repository, "package.json"), "utf8"),
  ) as { devDependencies?: Record<string, string> };
  const specifier = uiManifest.devDependencies?.["@hraness/design-kit"];
  assert.ok(
    typeof specifier === "string" && specifier.length > 0,
    "package.json must dev-depend on @hraness/design-kit",
  );
  const designKitManifest = JSON.parse(
    await readFile(
      resolve(repository, "node_modules/@hraness/design-kit/package.json"),
      "utf8",
    ),
  ) as { version?: unknown };
  assert.ok(
    typeof designKitManifest.version === "string",
    "Installed @hraness/design-kit must report a version",
  );

  const marks = askAiMarkIdentities.map(([provider, identity]) => {
    const mark = providerMark(identity);
    assert.ok(
      mark !== undefined,
      `The shared provider-mark registry must cover ${provider} (${identity}).`,
    );
    return [provider, { accent: mark.accent, art: mark.art, glyph: mark.glyph }] as const;
  });

  const body = JSON.stringify(Object.fromEntries(marks), null, 2);

  return `// Generated by scripts/sync-ask-ai-marks.ts from @hraness/design-kit
// ${designKitManifest.version} (${specifier}). Do not edit by hand; run
// \`bun run generate:ask-ai-marks\` after bumping the pinned design-kit release.
// Artwork provenance: vendor/provider-marks/UPSTREAM.md in the design-kit
// repository (Lobe Icons MIT, Charm FSL-1.1-MIT, original Aider mark).

export interface AskAiMarkArtwork {
  readonly body: string;
  readonly viewBox: string;
}

export interface AskAiProviderMark {
  readonly accent: string;
  readonly art: AskAiMarkArtwork | null;
  readonly glyph: AskAiMarkArtwork;
}

export const askAiProviderMarks = ${body} as const satisfies Readonly<Record<string, AskAiProviderMark>>;
`;
}

const rendered = await render();
if (process.argv.includes("--write")) {
  await writeFile(outputPath, rendered);
  console.log(`Wrote ${outputPath}`);
} else {
  const committed = await readFile(outputPath, "utf8").catch((error: unknown) => {
    if (typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  });
  assert.equal(
    committed,
    rendered,
    "src/ask-ai-marks.generated.ts is stale; run `bun run generate:ask-ai-marks` against the pinned @hraness/design-kit release.",
  );
  console.log("Ask AI provider marks match the pinned design-kit registry.");
}
