import * as stylex from "@stylexjs/stylex";

const compactViewport = "@media(max-width: 40rem)";
const forcedColors = "@media(forced-colors: active)";

export const contentStyles = stylex.create({
  actions: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "var(--space-2)",
    minWidth: 0,
  },
  emptyStateDescription: {
    color: "var(--ui-muted-foreground)",
    lineHeight: "var(--leading-body)",
    maxWidth: "36rem",
  },
  emptyStateIcon: {
    alignItems: "center",
    color: "var(--ui-muted-foreground)",
    display: "grid",
    fontSize: "var(--text-title)",
    justifyItems: "center",
  },
  emptyStateRoot: {
    alignItems: "center",
    borderColor: {
      default: "var(--ui-surface-edge)",
      [forcedColors]: "CanvasText",
    },
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: 1,
    borderRadius: "var(--radius-lg)",
    backgroundColor: "var(--ui-muted)",
    boxShadow: "var(--elevation-inset)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--ui-muted-foreground)",
    display: "grid",
    gap: "var(--space-3)",
    justifyItems: "center",
    minHeight: "12rem",
    paddingBlock: "var(--space-8)",
    paddingInline: "var(--space-8)",
    textAlign: "center",
  },
  emptyStateTitle: {
    color: "var(--ui-foreground)",
    fontSize: "var(--text-heading)",
    fontWeight: "var(--font-weight-bold)",
    lineHeight: "var(--leading-heading)",
  },
  inlineAlertBody: {
    minWidth: 0,
  },
  inlineAlertContent: {
    display: "grid",
    gap: "var(--space-1)",
    minWidth: 0,
  },
  inlineAlertDanger: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor:
      "color-mix(in oklch, var(--ui-destructive) 9%, var(--ui-card))",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    borderColor: {
      default:
        "color-mix(in oklch, var(--ui-destructive) 55%, var(--ui-border))",
      [forcedColors]: "CanvasText",
    },
  },
  inlineAlertIcon: {
    alignItems: "start",
    display: "grid",
    justifyItems: "center",
  },
  inlineAlertInfo: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--ui-info-soft)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    borderColor: {
      default: "var(--ui-border)",
      [forcedColors]: "CanvasText",
    },
  },
  inlineAlertRoot: {
    borderColor: {
      default: "var(--ui-border)",
      [forcedColors]: "CanvasText",
    },
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: 1,
    borderRadius: "var(--radius-lg)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--ui-card-foreground)",
    display: "grid",
    forcedColorAdjust: {
      default: null,
      [forcedColors]: "auto",
    },
    gap: "var(--space-3)",
    gridTemplateColumns: "auto minmax(0, 1fr)",
    paddingBlock: "var(--space-4)",
    paddingInline: "var(--space-4)",
  },
  inlineAlertSuccess: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--ui-success-soft)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    borderColor: {
      default:
        "color-mix(in oklch, var(--ui-success) 55%, var(--ui-border))",
      [forcedColors]: "CanvasText",
    },
  },
  inlineAlertTitle: {
    fontWeight: "var(--font-weight-bold)",
  },
  inlineAlertWarning: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--ui-warning-soft)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    borderColor: {
      default:
        "color-mix(in oklch, var(--ui-warning) 55%, var(--ui-border))",
      [forcedColors]: "CanvasText",
    },
  },
  pageIntroCopy: {
    display: "grid",
    gap: "var(--space-3)",
    maxWidth: "48rem",
  },
  pageIntroDescription: {
    color: "var(--ui-muted-foreground)",
    fontSize: "var(--text-body)",
    lineHeight: "var(--leading-body)",
    textWrap: "pretty",
  },
  pageIntroEyebrow: {
    color: "var(--ui-primary)",
    fontSize: "var(--text-caption)",
    fontWeight: "var(--font-weight-bold)",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  pageIntroRoot: {
    alignItems: {
      default: "end",
      [compactViewport]: "start",
    },
    display: "grid",
    gap: "var(--space-6)",
    gridTemplateColumns: {
      default: "minmax(0, 1fr) auto",
      [compactViewport]: "minmax(0, 1fr)",
    },
    maxWidth: "none",
  },
  pageIntroTitle: {
    color: "var(--ui-foreground)",
    fontSize: "clamp(var(--text-title), 5vw, var(--text-display))",
    fontWeight: "var(--font-weight-bold)",
    letterSpacing: "var(--tracking-display)",
    lineHeight: "var(--leading-display)",
    textWrap: "balance",
  },
  settingsCardBody: {
    minWidth: 0,
    paddingBlock: "var(--space-6)",
    paddingInline: "var(--space-6)",
  },
  settingsCardDescription: {
    color: "var(--ui-muted-foreground)",
    fontSize: "var(--text-label)",
    lineHeight: "var(--leading-label)",
    marginBlockStart: "var(--space-2)",
  },
  settingsCardHeader: {
    alignItems: "start",
    backgroundColor: "color-mix(in oklch, var(--ui-muted) 45%, var(--ui-card))",
    borderBlockEndColor: {
      default: "var(--ui-surface-edge)",
      [forcedColors]: "CanvasText",
    },
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: "1px",
    display: "flex",
    flexWrap: "wrap",
    gap: "var(--space-4)",
    justifyContent: "space-between",
    minWidth: 0,
    paddingBlock: "var(--space-6)",
    paddingInline: "var(--space-6)",
  },
  settingsCardRectangular: {
    borderRadius: "var(--radius-sharp)",
  },
  settingsCardRoot: {
    boxShadow: "var(--elevation-low)",
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--ui-card)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    borderColor: {
      default: "var(--ui-surface-edge)",
      [forcedColors]: "CanvasText",
    },
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: 1,
    borderRadius: "var(--radius-lg)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--ui-card-foreground)",
    overflow: "hidden",
  },
  settingsCardTitle: {
    fontSize: "var(--text-heading)",
    fontWeight: "var(--font-weight-bold)",
    lineHeight: "var(--leading-heading)",
  },
});
