import * as stylex from "@stylexjs/stylex";

const forcedColors = "@media (forced-colors: active)";
const reducedMotion = "@media (prefers-reduced-motion: reduce)";
const skeletonGradient =
  "linear-gradient(90deg, var(--ui-muted) 0%, color-mix(in oklch, var(--ui-muted) 72%, var(--ui-foreground)) 50%, var(--ui-muted) 100%)";

export const feedbackStyles = stylex.create({
  skeletonRoot: {
    animationComposition: { default: "replace", [reducedMotion]: "replace" },
    animationDelay: { default: "0s", [reducedMotion]: "0s" },
    animationDirection: { default: "normal", [reducedMotion]: "normal" },
    animationDuration: { default: "1.4s", [reducedMotion]: "0s" },
    animationFillMode: { default: "none", [reducedMotion]: "none" },
    animationIterationCount: { default: "infinite", [reducedMotion]: 1 },
    animationName: { default: "hraness-skeleton", [reducedMotion]: "none" },
    animationPlayState: { default: "running", [reducedMotion]: "running" },
    animationRangeEnd: { default: "normal", [reducedMotion]: "normal" },
    animationRangeStart: { default: "normal", [reducedMotion]: "normal" },
    animationTimeline: { default: "auto", [reducedMotion]: "auto" },
    animationTimingFunction: { default: "ease-in-out", [reducedMotion]: "ease" },
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: { default: "transparent", [forcedColors]: "Canvas" },
    backgroundImage: { default: skeletonGradient, [forcedColors]: "none" },
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: { default: "200% 100%", [forcedColors]: "auto auto" },
    borderBlockEndColor: { default: null, [forcedColors]: "CanvasText" },
    borderBlockEndStyle: { default: null, [forcedColors]: "solid" },
    borderBlockEndWidth: { default: null, [forcedColors]: "1px" },
    borderBlockStartColor: { default: null, [forcedColors]: "CanvasText" },
    borderBlockStartStyle: { default: null, [forcedColors]: "solid" },
    borderBlockStartWidth: { default: null, [forcedColors]: "1px" },
    borderImageOutset: { default: null, [forcedColors]: 0 },
    borderImageRepeat: { default: null, [forcedColors]: "stretch" },
    borderImageSlice: { default: null, [forcedColors]: "100%" },
    borderImageSource: { default: null, [forcedColors]: "none" },
    borderImageWidth: { default: null, [forcedColors]: 1 },
    borderInlineEndColor: { default: null, [forcedColors]: "CanvasText" },
    borderInlineEndStyle: { default: null, [forcedColors]: "solid" },
    borderInlineEndWidth: { default: null, [forcedColors]: "1px" },
    borderInlineStartColor: { default: null, [forcedColors]: "CanvasText" },
    borderInlineStartStyle: { default: null, [forcedColors]: "solid" },
    borderInlineStartWidth: { default: null, [forcedColors]: "1px" },
    borderRadius: "var(--radius-md)",
    minHeight: "1rem",
  },
  skeletonText: { borderRadius: "var(--radius-sm)", minHeight: "1em" },
  spinnerLarge: { fontSize: "1.5rem" },
  spinnerRoot: {
    animationComposition: { default: "replace", [reducedMotion]: "replace" },
    animationDelay: { default: "0s", [reducedMotion]: "0s" },
    animationDirection: { default: "normal", [reducedMotion]: "normal" },
    animationDuration: { default: "700ms", [reducedMotion]: "0s" },
    animationFillMode: { default: "none", [reducedMotion]: "none" },
    animationIterationCount: { default: "infinite", [reducedMotion]: 1 },
    animationName: { default: "hraness-spin", [reducedMotion]: "none" },
    animationPlayState: { default: "running", [reducedMotion]: "running" },
    animationRangeEnd: { default: "normal", [reducedMotion]: "normal" },
    animationRangeStart: { default: "normal", [reducedMotion]: "normal" },
    animationTimeline: { default: "auto", [reducedMotion]: "auto" },
    animationTimingFunction: { default: "linear", [reducedMotion]: "ease" },
    borderBlockEndColor: "color-mix(in oklch, currentColor 25%, transparent)",
    borderBlockEndStyle: "solid",
    borderBlockEndWidth: "0.125em",
    borderBlockStartColor: "currentColor",
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: "0.125em",
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: 1,
    borderInlineEndColor: "color-mix(in oklch, currentColor 25%, transparent)",
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: "0.125em",
    borderInlineStartColor: "color-mix(in oklch, currentColor 25%, transparent)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: "0.125em",
    borderRadius: "var(--radius-round)",
    display: "inline-block",
    height: "1em",
    width: "1em",
  },
  spinnerSmall: { fontSize: "0.75rem" },
});
