import * as stylex from "@stylexjs/stylex";

const coarsePointer = "@media(pointer: coarse)";
const compactViewport = "@media(max-width: 40rem)";
const syntheticCoarseMinimum = "var(--hraness-pagination-coarse-min, 0px)";

export const navigationStyles = stylex.create({
  breadcrumbCurrent: {
    color: "var(--ui-muted-foreground)",
    display: "block",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  breadcrumbCurrentItem: {
    flex: "1 1 auto",
  },
  breadcrumbItem: {
    alignItems: "center",
    display: "inline-flex",
    flex: "0 0 auto",
    gap: "var(--space-1)",
    minWidth: 0,
  },
  breadcrumbList: {
    alignItems: "center",
    display: "flex",
    flexWrap: "nowrap",
    gap: "var(--space-1)",
    listStyleImage: "none",
    listStylePosition: "outside",
    listStyleType: "none",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    minWidth: 0,
    overflow: "hidden",
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  breadcrumbRoot: {
    minWidth: 0,
  },
  breadcrumbSeparator: {
    "::before": {
      color: "var(--ui-muted-foreground)",
      content: '"/"',
      flex: "0 0 auto",
    },
  },
  paginationBoundary: {
    alignItems: "center",
    borderRadius: "var(--radius-md)",
    display: "inline-flex",
    justifyContent: "center",
    minHeight: {
      default: `max(var(--interactive-target-compact), ${syntheticCoarseMinimum})`,
      [coarsePointer]: "var(--interactive-target-min)",
    },
    paddingLeft: "var(--space-3)",
    paddingRight: "var(--space-3)",
  },
  paginationCurrent: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--ui-primary)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    color: "var(--ui-primary-foreground)",
  },
  paginationDisabled: {
    color: "var(--ui-muted-foreground)",
    cursor: "not-allowed",
    opacity: 0.6,
  },
  paginationEllipsis: {
    alignItems: "center",
    borderRadius: "var(--radius-md)",
    color: "var(--ui-muted-foreground)",
    display: "inline-flex",
    justifyContent: "center",
    minHeight: "var(--interactive-target-compact)",
    minWidth: "var(--interactive-target-compact)",
    paddingLeft: 0,
    paddingRight: 0,
  },
  paginationLink: {
    alignItems: "center",
    borderRadius: "var(--radius-md)",
    display: "inline-flex",
    justifyContent: "center",
    minHeight: {
      default: `max(var(--interactive-target-compact), ${syntheticCoarseMinimum})`,
      [coarsePointer]: "var(--interactive-target-min)",
    },
    minWidth: "var(--interactive-target-compact)",
    textDecoration: "none",
  },
  paginationList: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "var(--space-1)",
    justifyContent: "center",
    listStyleImage: "none",
    listStylePosition: "outside",
    listStyleType: "none",
    minWidth: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
  paginationRoot: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "var(--space-3)",
    justifyContent: {
      default: "space-between",
      [compactViewport]: "center",
    },
    listStyleImage: "none",
    listStylePosition: "outside",
    listStyleType: "none",
    minWidth: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
  },
});
