import * as stylex from "@stylexjs/stylex";

const coarsePointer = "@media(pointer: coarse)";
const compactViewport = "@media(max-width: 40rem)";
const forcedColors = "@media(forced-colors: active)";

export const toastStyles = stylex.create({
  region: {
    position: "fixed",
    zIndex: "var(--z-modal)",
    "inset-block-end": "max(var(--space-4), env(safe-area-inset-bottom))",
    "inset-inline-end": {
      default: "max(var(--space-4), env(safe-area-inset-right))",
      [compactViewport]: "max(var(--space-3), env(safe-area-inset-left))",
    },
    "inset-inline-start": {
      default: null,
      [compactViewport]: "max(var(--space-3), env(safe-area-inset-left))",
    },
    display: "flex",
    width: {
      default: "min(26rem, calc(100vw - 2rem))",
      [compactViewport]: "auto",
    },
    maxHeight: "calc(100dvh - 2rem)",
    flexDirection: "column",
    gap: "var(--space-2)",
    outlineColor: "currentColor",
    outlineStyle: "none",
    outlineWidth: "medium",
    pointerEvents: "none",
  },
  root: {
    position: "relative",
    display: "grid",
    minWidth: 0,
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gap: "var(--space-3)",
    paddingTop: "var(--space-4)",
    paddingRight: "var(--space-4)",
    paddingBottom: "var(--space-4)",
    paddingLeft: "var(--space-4)",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: {
      default: "var(--ui-border)",
      [forcedColors]: "CanvasText",
    },
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: 1,
    borderRadius: "var(--radius-lg)",
    outlineColor: "currentColor",
    outlineStyle: "none",
    outlineWidth: "medium",
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--ui-popover)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    color: "var(--ui-popover-foreground)",
    boxShadow: "var(--elevation-overlay)",
    pointerEvents: "auto",
    forcedColorAdjust: {
      default: null,
      [forcedColors]: "auto",
    },
  },
  entering: {
    animationDuration: "var(--motion-duration-standard)",
    animationTimingFunction: "var(--motion-easing-emphasized)",
    animationDelay: "0s",
    animationIterationCount: 1,
    animationDirection: "normal",
    animationFillMode: "none",
    animationPlayState: "running",
  },
  toneDanger: {
    borderColor: {
      default: "color-mix(in oklch, var(--ui-destructive) 55%, var(--ui-border))",
      [forcedColors]: "CanvasText",
    },
  },
  toneInfo: {
    borderColor: {
      default: "color-mix(in oklch, var(--ui-info) 55%, var(--ui-border))",
      [forcedColors]: "CanvasText",
    },
  },
  toneSuccess: {
    borderColor: {
      default: "color-mix(in oklch, var(--ui-success) 55%, var(--ui-border))",
      [forcedColors]: "CanvasText",
    },
  },
  toneWarning: {
    borderColor: {
      default: "color-mix(in oklch, var(--ui-warning) 55%, var(--ui-border))",
      [forcedColors]: "CanvasText",
    },
  },
  content: {
    display: "flex",
    minWidth: 0,
    flexWrap: "wrap",
    alignItems: "center",
    gap: "var(--space-3)",
  },
  copy: {
    display: "grid",
    minWidth: 0,
    flex: "1 1 12rem",
    gap: "var(--space-1)",
  },
  title: {
    fontWeight: "var(--font-weight-bold)",
    lineHeight: 1.3,
  },
  description: {
    color: "var(--ui-muted-foreground)",
    fontSize: "var(--text-label)",
    lineHeight: 1.5,
  },
  action: {
    flex: "0 0 auto",
  },
  close: {
    display: "inline-grid",
    width: "var(--interactive-target-compact)",
    minWidth: "var(--interactive-target-compact)",
    minHeight: {
      default: "max(var(--interactive-target-compact), var(--hraness-toast-coarse-min, 0px))",
      [coarsePointer]: "var(--interactive-target-min)",
    },
    alignItems: "center",
    justifyItems: "center",
    alignSelf: "start",
    borderWidth: 0,
    borderStyle: "none",
    borderColor: "currentColor",
    borderImageOutset: 0,
    borderImageRepeat: "stretch",
    borderImageSlice: "100%",
    borderImageSource: "none",
    borderImageWidth: 1,
    borderRadius: "var(--radius-md)",
    outlineColor: "currentColor",
    outlineStyle: "none",
    outlineWidth: "medium",
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "transparent",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    color: "var(--ui-muted-foreground)",
  },
  closeHovered: {
    backgroundAttachment: "scroll",
    backgroundClip: "border-box",
    backgroundColor: "var(--ui-accent)",
    backgroundImage: "none",
    backgroundOrigin: "padding-box",
    backgroundPosition: "0% 0%",
    backgroundRepeat: "repeat",
    backgroundSize: "auto auto",
    color: "var(--ui-accent-foreground)",
  },
  closeFocusVisible: {
    outlineColor: "var(--ui-ring)",
    outlineStyle: "solid",
    outlineWidth: "2px",
    outlineOffset: "2px",
  },
  closeNativeInteractionFallbacks: {
    backgroundAttachment: { default: null, ":hover": "scroll" },
    backgroundClip: { default: null, ":hover": "border-box" },
    backgroundColor: { default: null, ":hover": "var(--ui-accent)" },
    backgroundImage: { default: null, ":hover": "none" },
    backgroundOrigin: { default: null, ":hover": "padding-box" },
    backgroundPosition: { default: null, ":hover": "0% 0%" },
    backgroundRepeat: { default: null, ":hover": "repeat" },
    backgroundSize: { default: null, ":hover": "auto auto" },
    color: { default: null, ":hover": "var(--ui-accent-foreground)" },
    outlineColor: { default: null, ":focus-visible": "var(--ui-ring)" },
    outlineStyle: { default: null, ":focus-visible": "solid" },
    outlineWidth: { default: null, ":focus-visible": "2px" },
    outlineOffset: { default: null, ":focus-visible": "2px" },
  },
});
